# Generated by Django 5.2.3 on 2025-06-13 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descrcao',
            new_name='descricao',
        ),
    ]
